In [1]:
import pandas as pd
import random
import string

Genero 20 advertiser_id activos y 5 inactivos

In [2]:
random.seed(4)
active_advertisers = [''.join(random.choices(string.ascii_uppercase + string.digits, k = 20)) for _ in range(20)]
inactive_advertisers = [''.join(random.choices(string.ascii_uppercase + string.digits, k = 20)) for _ in range(5)]
all_advertisers = active_advertisers+inactive_advertisers

In [3]:
active_advertisers

['IDOFCO721HTJGDH7332G',
 'LW045DVYSGRD75TK6U54',
 'SOVPFK3BBWKTQM9HOHWJ',
 'M0LU6DCI1WILGQBZ6808',
 'AK81O7W3KGPEN8LABG2N',
 'KD9PHCBGYFBRI9ET1O9R',
 'IOBPI63RBJIHI5FB7U9O',
 '6X20RDH567MX2X3TXYJ7',
 '8C88YB6E8YCGWU07HA7A',
 '5E325T5HYL61QSABVR5V',
 'EN1SA43DTN2LIR8DEW5S',
 'P41C5HK4P2G5GFRMT6ZA',
 'LTRZRCI4M19WYVL6Q6L5',
 '2WPF1NXECF3G6NUMWDO7',
 'GXLKAA83238FVRU718EX',
 'Y0W3K7OV6ZLILW96OO3K',
 'OAGTYWN8WFC997VLDJH7',
 '62FIK8F2YT8JSFDBLEC9',
 'K6Z0X85ZUY0TSF4RCG5J',
 'OY5LNPB5A8FF43ITRZG3']

In [4]:
pd.DataFrame(active_advertisers, columns=['advertiser_id']).to_csv('advertiser_ids', index=False)

Genero un catalogo de 100 productos para cada uno de los advertisables

In [5]:
advertisers_catalogs = {}
for advertiser in all_advertisers:
    advertisers_catalogs[advertiser] = [''.join(random.choices(string.ascii_lowercase + string.digits, k = 6)) for _ in range(100)]

In [6]:
possible_dates = [f'2026-04-{day:02d}' for day in range(18,31)] + [f'2026-05-{day:02d}' for day in range(1,30)]

In [7]:
possible_dates

['2026-04-18',
 '2026-04-19',
 '2026-04-20',
 '2026-04-21',
 '2026-04-22',
 '2026-04-23',
 '2026-04-24',
 '2026-04-25',
 '2026-04-26',
 '2026-04-27',
 '2026-04-28',
 '2026-04-29',
 '2026-04-30',
 '2026-05-01',
 '2026-05-02',
 '2026-05-03',
 '2026-05-04',
 '2026-05-05',
 '2026-05-06',
 '2026-05-07',
 '2026-05-08',
 '2026-05-09',
 '2026-05-10',
 '2026-05-11',
 '2026-05-12',
 '2026-05-13',
 '2026-05-14',
 '2026-05-15',
 '2026-05-16',
 '2026-05-17',
 '2026-05-18',
 '2026-05-19',
 '2026-05-20',
 '2026-05-21',
 '2026-05-22',
 '2026-05-23',
 '2026-05-24',
 '2026-05-25',
 '2026-05-26',
 '2026-05-27',
 '2026-05-28',
 '2026-05-29']

Genero lineas de vistas de producto

In [8]:
product_views = [[advertiser := random.choice(all_advertisers), random.choice(advertisers_catalogs[advertiser]), random.choice(possible_dates)] for _ in range(100_000)]

In [9]:
df_product_views = pd.DataFrame(product_views, columns=['advertiser_id', 'product_id', 'date'])

In [10]:
df_product_views = df_product_views.sort_values('date').reset_index(drop=True)

In [11]:
df_product_views.head(20)

           advertiser_id product_id        date
0   M0LU6DCI1WILGQBZ6808     w6v0bb  2026-04-18
1   1OW4LWJSBJK6E1D9FDH7     d001sh  2026-04-18
2   OAGTYWN8WFC997VLDJH7     xk7091  2026-04-18
3   62FIK8F2YT8JSFDBLEC9     pacgwu  2026-04-18
4   2WPF1NXECF3G6NUMWDO7     mgktm4  2026-04-18
5   M0LU6DCI1WILGQBZ6808     i51lu3  2026-04-18
6   M0LU6DCI1WILGQBZ6808     9326s4  2026-04-18
7   P41C5HK4P2G5GFRMT6ZA     rho0gy  2026-04-18
8   6X20RDH567MX2X3TXYJ7     or5lid  2026-04-18
9   LTRZRCI4M19WYVL6Q6L5     joka8q  2026-04-18
10  2WPF1NXECF3G6NUMWDO7     jwanpi  2026-04-18
11  8C88YB6E8YCGWU07HA7A     94xh2d  2026-04-18
12  2WPF1NXECF3G6NUMWDO7     59j88y  2026-04-18
13  03KNVBO915KY2ZPGA57J     r9u539  2026-04-18
14  M0LU6DCI1WILGQBZ6808     2nnq5l  2026-04-18
15  SOVPFK3BBWKTQM9HOHWJ     73k7gz  2026-04-18
16  1OW4LWJSBJK6E1D9FDH7     8jzxvy  2026-04-18
17  5E325T5HYL61QSABVR5V     b5uafp  2026-04-18
18  KD9PHCBGYFBRI9ET1O9R     s1ncbm  2026-04-18
19  2WPF1NXECF3G6NUMWDO7     5u0fz3  2026-04-18

In [12]:
df_product_views.to_csv('product_views', index=False)

Genero lineas de vistas de ads

In [13]:
ads_views = [[advertiser := random.choice(all_advertisers), random.choice(advertisers_catalogs[advertiser]), random.choices(['impression', 'click'], weights=[99, 1])[0], random.choice(possible_dates)] for _ in range(100_000)]

In [14]:
df_ads_views = pd.DataFrame(ads_views, columns=['advertiser_id', 'product_id', 'type', 'date'])

In [15]:
df_ads_views = df_ads_views.sort_values('date').reset_index(drop=True)

In [16]:
df_ads_views.head(20)

           advertiser_id product_id        type        date
0   2WPF1NXECF3G6NUMWDO7     athjhi  impression  2026-04-18
1   IOBPI63RBJIHI5FB7U9O     lq50zx  impression  2026-04-18
2   9Z77N44VDW6KX6VBWJ4X     d08ikb  impression  2026-04-18
3   Y0W3K7OV6ZLILW96OO3K     mqbb0z  impression  2026-04-18
4   OAGTYWN8WFC997VLDJH7     38y7f3  impression  2026-04-18
5   SOVPFK3BBWKTQM9HOHWJ     c6nfma  impression  2026-04-18
6   K6Z0X85ZUY0TSF4RCG5J     xmu2qk  impression  2026-04-18
7   AK81O7W3KGPEN8LABG2N     doayj7  impression  2026-04-18
8   SOVPFK3BBWKTQM9HOHWJ     m76e67  impression  2026-04-18
9   M0LU6DCI1WILGQBZ6808     bjxh8k  impression  2026-04-18
10  Y0W3K7OV6ZLILW96OO3K     44m3jj  impression  2026-04-18
11  IOBPI63RBJIHI5FB7U9O     r8yxfp  impression  2026-04-18
12  03KNVBO915KY2ZPGA57J     0zmyxz  impression  2026-04-18
13  KD9PHCBGYFBRI9ET1O9R     aosbxv  impression  2026-04-18
14  IDOFCO721HTJGDH7332G     f1mbh0  impression  2026-04-18
15  KD9PHCBGYFBRI9ET1O9R     hq6knq  impression  2026-04-18
16  AK81O7W3KGPEN8LABG2N     604g3a  impression  2026-04-18
17  EN1SA43DTN2LIR8DEW5S     hzgf9w  impression  2026-04-18
18  03KNVBO915KY2ZPGA57J     z4pnuj  impression  2026-04-18
19  OAGTYWN8WFC997VLDJH7     a29avi  impression  2026-04-18

In [17]:
df_ads_views.to_csv('ads_views', index=False)